### ISSUE TITLE
failed to set cell value warning when cell value is json string

### ISSUE THREAD

**Issue by motivatedmind** [osglworks/java-excel#22]
I am using `<version>1.4.0</version>` 

One of the cell has json string for which I get such warning

`[main] WARN org.osgl.xls.ExcelReader - failed to set cell value[{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}] to POJO[class com.example.excel.Model]: K2@[mySheet]
org.osgl.exception.UnexpectedException: java.lang.NumberFormatException: For input string: "{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
}"
	at org.osgl.util.E.unexpected(E.java:189)
	at org.osgl.util.ReflectionPropertySetter.setProperty(ReflectionPropertySetter.java:58)
	at org.osgl.util.ReflectionPropertySetter.set(ReflectionPropertySetter.java:47)
	at org.osgl.xls.ExcelReader.read(ExcelReader.java:157)
	at org.osgl.xls.ExcelReader.read(ExcelReader.java:122)
	at org.osgl.xls.ExcelReader.read(ExcelReader.java:82)`

My reader code as below

`ExcelReader.builder()
        .sheets("mySheet")
        .file(new File("myExcel.xlsx"))
        .build().read(Model.class)`

Is there something I am missing?

**Comment by greenlaw110** [comment]
@motivatedmind do you minding sharing the `myExcel.xlsx` and source code of `Model` class here?

**Comment by motivatedmind** [comment]
Here is a minimum example : https://github.com/motivatedmind/osglworks-java-excel-issue-22

**Comment by greenlaw110** [comment]
@motivatedmind 

Here in your code, specifically the `Model` class, `expectedResponse` is defined as an `Integer`:

![image](https://user-images.githubusercontent.com/216930/93327918-5e3ea700-f85e-11ea-949c-fc634f202243.png)

However, in your Excel file, the `Expected Response` column is obviously not an integer:

![image](https://user-images.githubusercontent.com/216930/93328067-90500900-f85e-11ea-8116-4911eba5a0a7.png)

Once you change your `expectedResponse` type from `Integer` to `String` the issue is gone, and the program exit with code `0`:

![image](https://user-images.githubusercontent.com/216930/93328222-ce4d2d00-f85e-11ea-958a-d699cd2a74e1.png)

**Comment by motivatedmind** [comment]
@greenlaw110  Hey Thanks a ton. Realized my mistake. 

I have one more questions what exactly this means "[main] WARN org.osgl.xls.ExcelReader - column index not fully built on sheet:"

**Comment by greenlaw110** [comment]
@motivatedmind it's a warning message triggered when the number of columns in your excel sheet is less than the number of fields in your Model class.

BTW, you are using the obsolete `excel-reader` dependency, you should replace it with `osgl-excel` instead:

https://search.maven.org/artifact/org.osgl/osgl-excel/1.10.2/jar

**Comment by motivatedmind** [comment]
Hey Thanks, I get that. 
I will update to latest dependency. But your documentation points to older `excel-reader`. 
Would you consider enhancement to write POJO to excel as well. Natively apache poi expects to do cell by cell by iterating.
Anyways I really appreciate your efforts for this nice library, really helped me !!!

**Comment by greenlaw110** [comment]
@motivatedmind osgl-excel has write support built in. Just use `ExcelWriter.Builder` to create a Writer instance, and call `writer.write` method to output your data to Excel file.

If you are using [ActFramework](https://github.com/actframework/actframework) then things is even easier, just reture your data, the framework can export excel file when request Accept header is [excel mime type](https://stackoverflow.com/questions/974079/setting-mime-type-for-excel-document)

**Comment by greenlaw110** [comment]
You can find the usage of ExcelWriter at https://github.com/osglworks/java-excel/blob/master/src/test/java/org/osgl/xls/ExcelWriterTest.java

**Comment by motivatedmind** [comment]
Thanks a lot !!!
